### ISSUE TITLE
Support PrimaryLanguageOverride from unpackaged apps

### ISSUE THREAD

**Issue by shelllet** [microsoft/WindowsAppSDK#1687]
when calling the following code from an unpackaged app, it throws an error. This is needed to be able to use `x:Uid` localization in XAML and control the language it picks.
```
App::App()
{
    ...
    Windows::Globalization::ApplicationLanguages::PrimaryLanguageOverride(...)
    ...
}
```

**Comment by btueffers** [comment]
Hi @shelllet, this API isn't intended to work from an unpackaged context.

**Comment by andrewleader** [comment]
Additionally, we've started a list of APIs like this that don't work from unpackaged apps that we need to either (1) document better with warnings so you know before you try using it, or (2) add new WinAppSDK APIs that work for unpackaged apps: #1702

**Comment by shelllet** [comment]
So what Api should I call to set the defualt language?

**Comment by andrewleader** [comment]
@axelandrejs how should unpackaged apps set their default language for resolving resources and XAML localization?

**Comment by huichen123** [comment]
MRTCore determines the default language using Windows::Globalization::ApplicationLanguages::Languages (https://github.com/microsoft/WindowsAppSDK/blob/main/dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp#L106-L113)

**Comment by andrewleader** [comment]
@huichen123 yes, and how should unpackaged apps change the default language for their app? As shelllet asked, in a packaged app, developers can call `ApplicationLanguages::PrimaryLanguageOverride('en-us')` to override the default language, but that API doesn't work for unpackaged apps. How should unpackaged apps override the default language when using MRT Core?

Many apps (including my own) allow the user to pick their own language independent from the OS language.

**Comment by huichen123** [comment]
Before PrimaryLanguageOverride is fixed, you may have to pass in a ResourceContext, and set its Language qualifier value to the desired value.

**Comment by seven-mile** [comment]
> Before PrimaryLanguageOverride is fixed, you may have to pass in a ResourceContext, and set its Language qualifier value to the desired value.

Will these unpackaged API be fixed before GA version? This breaks x:Uid localization and seems to have no workaround.

**Comment by huichen123** [comment]
sorry, it will not be fixed for GA.

**Comment by andrewleader** [comment]
Re-opening this, as it's something we should implement at least someday so that unpackaged apps can use XAML `x:Uid` localization and control the language the app uses.

Tagging it as a bug too, this definitely is somewhere between bug and "feature", but since the overall scenario of localizing your unpackaged app with control over the language doesn't work, I'll add the bug tag.

**Comment by ghost1372** [comment]
Hi @andrewleader 
any news?
can we expect this feature/bugfix in WASDK 1.1/preview/experimental?

**Comment by andrewleader** [comment]
@huichen123 is the owner of this feature/bug and maybe can speak toward whether this would be in 1.1.

And FYI Mahdi, I moved to a different project in Microsoft, the right person to contact with general WinAppSDK questions would be **marb2000**. Thanks!

**Comment by seven-mile** [comment]
@huichen123  Hi! Any news on this? Convenient globalization is an indispensable feature for unpackaged apps to use WinAppSDK. 😋

**Comment by axelandrejs** [comment]
> Windows.Globalization.ApplicationLanguages was designed for packaged app. Instead of inventing local settings for unpackaged app, it might be easier WinUI can take ResourceManager/ResourceContext from app. @evelynwu-msft ?

Agreed with this. Language is not the only interesting setting here. EG, what about scale or theme? The way to set these is via the context, so that context should be exposed.

**Comment by Iris0905** [comment]
Hello, is there any update on when will this be implemented? Currently, there is no easy way to localize the strings in XAML for an unpackaged app, which is very frustrating😞

**Comment by AndrewKeepCoding** [comment]
As a workaround, I have a [NuGet package](https://github.com/AndrewKeepCoding/AK.Toolkit#-localizer) that also works with unpackaged apps. It's uses the general **Resources.resw** strings, so you should be able to switch back when the WinUI team comes with a solution 😎

**Comment by sylveon** [comment]
I am hitting this issue when attempting to support language changes from an unpackaged XAML islands (non-WinUI 3) app. The API works as expected when the app is packaged. What should I do? I don't think system XAML uses MRTCore.

**Comment by Blinue** [comment]
Is anyone working on this?

**Comment by ghost1372** [comment]
any news?
@evelynwu-msft 
we are in 1.4-preview1 and we cant change app language!

**Comment by ghost1372** [comment]
good news
https://github.com/microsoft/WindowsAppSDK/pull/4181

**Comment by sylveon** [comment]
Doesn't solve my problem :(

**Comment by stefansjfw** [comment]
> I am hitting this issue when attempting to support language changes from an unpackaged XAML islands (non-WinUI 3) app. The API works as expected when the app is packaged. What should I do? I don't think system XAML uses MRTCore.

@sylveon Can you provide a sample app? Thanks.

**Comment by sylveon** [comment]
Any app using system XAML islands will fail when trying to use `Windows::Globalization::ApplicationLanguages::PrimaryLanguageOverride` without being packaged. WASDK cannot solve this without a complete migration to WinUI 3, which is non-trivial.

**Comment by ghost1372** [comment]
@duncanmacmichael i tested with v1.6-exp2 and now we can use
Microsoft.Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = "fa-IR";
and everything is working fine, and i think this issue can be closed

**Comment by codendone** [comment]
Thanks, @ghost1372!

Closing as fixed in [1.6.240701003-experimental2](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.6.240701003-experimental2) via microsoft/WindowsAppSDK#4523.

**Comment by TheVoidSeeker** [comment]
I'm using 1.6.240701003-experimental2 in my unpackaged app and it still doesn't work.
It causes a COMException with message 'No such interface supported'

**Comment by AndrewKeepCoding** [comment]
@TheVoidSeeker 
You can see the localization in action in this [video](https://youtu.be/_Fgikgr7sno?si=H-dmflkAAmzV7O2G).

**Comment by ghost1372** [comment]
> I'm using 1.6.240701003-experimental2 in my unpackaged app and it still doesn't work.
> It causes a COMException with message 'No such interface supported'

Show your codes, because i am using in unpackaged without issues

**Comment by TheVoidSeeker** [comment]
After repairing my Visual Studio installation and cleaning all intermediate and output files, it now works without code changes.
Not sure what was happening there.

I did Clean & Rebuild of the project several times yesterday, but still always got the mentioned error.
I'm very glad that it finally works, as this is a very important use case for our customers.

Thanks a lot for your work!

**Comment by Galebra** [comment]
> [@TheVoidSeeker](https://github.com/TheVoidSeeker) You can see the localization in action in this [video](https://youtu.be/_Fgikgr7sno?si=H-dmflkAAmzV7O2G).
@AndrewKeepCoding 
I tested what you show in the video and the primary override does not get persisted in a packaged Winui 3 on 1.8. What happened between the versions?
