### ISSUE TITLE
I've spent a few hours debugging this. Here's what's going wrong and how to work around it.

### ISSUE THREAD

**Issue by kinkycat91** [microsoft/WindowsAppSDK#1732]
I've spent a few hours debugging this. Here's what's going wrong and how to work around it.

This looks like a (very serious!!) bug in the MSIX / Delivery Optimization subsystem of Windows. It appears Microsoft already know about it and have fixed it back in May, but haven't yet released the fix, at least not to Windows 10. 

@wcheng-msft @samiranshah  You guys need to document the bug and publish an official workaround if you aren't going to push out the fix ASAP because this is a nightmare to figure out, yet you clearly already know what the bug is! That's really not a satisfying discovery.

The Delivery Optimization subsystem that is used by App Installer appears to be incorrectly caching the *size* of the file given a URL, in memory. If an `.appinstaller` file changes its size once published, then any machine that already downloaded it will try to download the exact same number of bytes as previously retrieved until the in memory cache is cleared with a reboot. This will result in one of two things happening:

1. Windows requests more bytes than actually exist in the file, and then thinks - wrongly - the server doesn't support Range queries when it doesn't get enough bytes. It reports error 0x80D05011 which is "DO_E_INSUFFICIENT_RANGE_SUPPORT" as a consequence.
2. Windows requests *fewer* bytes than actually exist, resulting in an attempt to parse truncated XML. This can show up in a variety of ways.

@yowl  This is why you see the failure once you changed the version number. The problem is not actually the change of version number but rather that the new version quad is a different size textually to the previous.

The situation _may_ be complicated by HTTP redirects. I saw this problem myself before ever changing anything about the XML, and I think Windows cached the wrong size from the body of a 302 redirect from HTTP to HTTPS. So watch out for that if your server generates a lot of HTML when issuing redirects.

You can see that this bug is happening by dumping the Delivery Optimization subsystem logs: `Get-DeliveryOptimizationLog | Set-Content c:\dosvc.log` then look at the end. If you study it _very carefully_ you will notice that the size of the request that is being made is different to the actual size of the file on your web server.

Here's a stupid hack that seems to work: always pad the file with white space to a size large enough that you'll never exceed it. If your XML grows, it'll eat into the white space which the XML parser will ignore. If it shrinks, add more whitespace to re-pad it to the old length. I'm generating the AppInstaller .XML myself rather than using any Microsoft tool so I can do this easily - if you aren't then you may need a custom script.

__Originally posted by @mikehearn in https://github.com/MicrosoftDocs/msix-docs/issues/188#issuecomment-947934682__

**Comment by riverar** [comment]
Yeah this is a well known bug that was fixed afaik. I am a little surprised to hear this wasn't serviced. Maybe @jvintzel can chine in here.

**Comment by gtoison** [comment]
@riverar that issue has affected us for a while now and upgrading to the newer W10 builds does not solve it. Appinstaller is otherwise very neat so it's a bit unfortunate.
There's a long discussion here: https://techcommunity.microsoft.com/t5/msix-deployment/windows-10-2004-msix-not-updating-please-check-whether-the/m-p/1466701

**Comment by andrewleader** [comment]
@DrusTheAxe would this issue be your area space? Or should we get the AppInstaller team to look into it?

**Comment by mikehearn** [comment]
Supposedly a fix has already entered the update stream but some of us don't seem to have it. Or maybe we do now - there was an update a few days ago and I haven't bothered re-testing since that.

Regardless, Windows updates take time to propagate, so the workaround will be required for (my guess) a year or two at least, for people who don't control the Windows versions of their users. I would suggest documenting it somewhere, in the troubleshooting section of the docs for example.

**Comment by yowl** [comment]
I'm trying a combination of things, its a poor situation really.  I have the size fix from @mikehearn, plus I'm also trying to a manual add-appxpackage on shutdown of the app, if the app has detected this problem.  I've yet to try this approach in the wild though so don't know how successful it will be.  Have to try something, cant keep asking users to reinstall.

**Comment by charlesjIV** [comment]
Ya, restarting a service or the computer isn't a real solution. Do you happen to have the size fix link? @yowl

**Comment by yowl** [comment]
@charlesjIV this is the powershell that I use to fix the size of the xml:

https://github.com/MicrosoftDocs/msix-docs/issues/188#issuecomment-947967085

**Comment by charlesjIV** [comment]
Is that still working for you? I tried that solution and it didn't seem to change anything. Do you have the script in your build pipeline or your release?

**Comment by yowl** [comment]
@charlesjIV No, not always.  I think its fine for the Delivery Optimisation caching bug (that can also be fixed by a reboot), but I believe there is another bug that will prevent the appx from even attempting to check for a new version.  This later one I'm attempting to fix by running `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
-NonInteractive -WindowStyle Hidden -Command "add-appxpackage -appinstaller https://xxxxx/yyy.appinstaller"` on shutdown.  This might be working at least in some scenarios, its too early to say (although it still needs 2 restarts of the application, but at least the users can do that without help from IT).

**Comment by yowl** [comment]
I have the script in the build pipeline.

**Comment by charlesjIV** [comment]
@yowl do you have the script after the Create App Installer MSIX job?

**Comment by yowl** [comment]
Yes, it’s the step before publishing the artifact.

**Comment by charlesjIV** [comment]
@yowl  How did you run the powershell script on process quit? I am new to packaging and app deployment. Sorry for all the questions.

**Comment by yowl** [comment]
@charlesjIV No problem.  When the app starts I start a thread and check the status using `RequestAddPackageByAppInstallerFileAsync`  If that returns Unknown, then I set a flag indicating that when the app shuts down it should run the fix up script (which may or not work).  I use code from http://csharptest.net/?p=526 and http://csharptest.net/?p=529 to do that.  Basically this:
```
                    ProcessStartInfo psi = new ProcessStartInfo();
                    psi.UseShellExecute = false;
                    psi.RedirectStandardError = true;
                    psi.RedirectStandardOutput = true;
                    psi.WindowStyle = ProcessWindowStyle.Hidden;
                    psi.CreateNoWindow = true;
                    psi.ErrorDialog = false;
                    psi.WorkingDirectory = Environment.CurrentDirectory;
                    psi.FileName = FindExePath("powershell.exe"); //see http://csharptest.net/?p=526
                    psi.Arguments = EscapeArguments("-NonInteractive", "-WindowStyle", "Hidden", "-Command", "add-appxpackage -appinstaller " + ConfigurationManager.AppSettings["installUri"]); // see http://csharptest.net/?p=529


                    Process process = Process.Start(psi);
```

**Comment by yowl** [comment]
Oh, and best not check immediately when the app starts, as it might actually be working and doing an update or checking for an update, so I wait a few minutes.

**Comment by charlesjIV** [comment]
Do you not get an error saying that the appinstaller can't install because it is in use?

**Comment by yowl** [comment]
Yes, there is https://techcommunity.microsoft.com/t5/msix-sdk/appx-appinstaller-requestaddpackagebyappinstallerfileasync/m-p/2911575 but I haven't got round to sending the logs.

**Comment by charlesjIV** [comment]
@yowl so that powershell script that runs on application close how is it going and getting the new appinstaller file from the URL because mine comes back saying that it can't install the new file due to the appinstaller file already being open to run the application. Or are you starting a service or something after the application closes to actually run the powershell script?

**Comment by yowl** [comment]
We store it in the app.confg.  Not ideal, but I couldn't see how the built in mechanism gets it.  And yes, we start the process when application exits.

**Comment by charlesjIV** [comment]
How do you start it?

**Comment by yowl** [comment]
Hook the exit event
```
                App.Instance.Exit += InstanceOnExit;
```

**Comment by charlesjIV** [comment]
System.Windows.Forms.Application.ApplicationExit += Shutdown; 

  private void Shutdown(object sender, EventArgs e) {
            ProcessStartInfo psi = new ProcessStartInfo();
            psi.UseShellExecute = false;
            psi.RedirectStandardError = true;
            psi.RedirectStandardOutput = true;
            psi.WindowStyle = ProcessWindowStyle.Hidden;
            psi.CreateNoWindow = true;
            psi.ErrorDialog = false;
            psi.WorkingDirectory = Environment.CurrentDirectory;
            psi.FileName = FindExePath("powershell.exe"); //see http://csharptest.net/?p=526
            psi.Arguments = EscapeArguments("-NonInteractive", "-WindowStyle", "Hidden", "-Command", "add-appxpackage -appinstaller " + "https://xxx.appinstaller"); // see http://csharptest.net/?p=529
            Process process = Process.Start(psi);
        }
So something like this right?

**Comment by yowl** [comment]
Yes, You probably don’t need to bother with redirecting the output, but we use the same code for checking in an “About” screen where we want to see what happens.

**Comment by charlesjIV** [comment]
Ok cool. That finally worked. I am using Caliburn micro and I was attempting to do the exit event in the MainViewModel but I needed to do it in the bootstrapper I think. I am testing a build now to see what happens.

**Comment by charlesjIV** [comment]
@yowl One more question for you. You said you were using the RequestAddPackageByAppInstallerFileAsync() and that requires a Package Volume. Did you install your appinstaller into a package volume or is there another way to get that directory. Or do you just pass in null or something to that method.

**Comment by yowl** [comment]
Pass null for that.
