### ISSUE TITLE
Unable to package app for Microsoft Store, because: "error: The app manifest must be valid as per schema. Reason: Required attribute 'PhonePublisherId' is missing."

### ISSUE THREAD

**Issue by Qws** [microsoft/WindowsAppSDK#2703]
### Describe the bug

I created an app with WinAppSDK/WinUI3 template (without WinForm and Wpf) 

I tried to publish the app by left clicking the Project file and select "Associate with with Store" or "Create app package..." but it gets halted very quickly. Because:

`Error		0x80080204 - The specified package format is not valid: The package manifest is not valid.`

&

`Error info: error C00CE020: App manifest validation error: The app manifest must be valid as per schema: Line 35, Column 4, Reason: Required attribute 'PhonePublisherId' is missing.`

After I did that, I could not debug my app anymore either.

Because of:

![image](https://user-images.githubusercontent.com/3944421/177305716-551b8e44-ad23-4146-91d0-6ad39b85e6c8.png)

&

`DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE020: App manifest validation error: The app manifest must be valid as per schema: Line 35, Column 4, Reason: Required attribute 'PhonePublisherId' is missing.
`

so the only way the debug the app again is to revert the changes made by the "Associate with the Store / Create app package".

And I still can't publish my app to Microsoft Store. I've uploaded my UWP apps with no problems to Microsoft Store, I can't do this with WinAppSDK/WinUI3.

### Steps to reproduce the bug

1. Create Windows App SDK + WinUI3 Project
2.  In Project leftclick menu, select "Associate the app with the Store" or ... "Create app package".

![image](https://user-images.githubusercontent.com/3944421/177309301-f4c527ff-c666-4aef-a904-7e77e481e0ff.png)

3. Follow the wizard steps to make package for Microsoft Store.

Until it gets aborted for this:
![image](https://user-images.githubusercontent.com/3944421/177309995-a909d963-7a08-4303-bd32-2a8d92f3e8d4.png)

### Expected behavior

I've released few UWP apps in the Store, and I keep maintaining them regularly, I've no problems with it... but with Windows App SDK it doens't work at all.

### NuGet package version

1.1.1

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022-preview

### Additional context

I don't remember which WinUI3 template I used... I just picked one and started developing.

**Comment by Qws** [comment]
Oke I fixed my issue by adding: `PhonePublisherId="00000000-0000-0000-0000-000000000000"` in the PackageManifest's `<mp:PhoneIdentity />`

I guess this is a bug and needs to be automated?

**Comment by riverar** [comment]
Related: https://github.com/MicrosoftDocs/winrt-related/issues/19

**Comment by DrusTheAxe** [comment]
> @sachintaMSFT Santosh Chintalapati FTE tag you're it

@sachintaMSFT Was this fixed in the servicing update?

**Comment by sachintaMSFT** [comment]
This seems to be an issue with WinUI3 template not adding phone publisher ID automatically to the manifest of the app being created. This is not an issue with the WinAppSDK packages itself. @MikeHillberg , who should look at this WinUI 3 template issue ?

**Comment by LancerComet** [comment]
Encountered this problem, can't believe this is still not being fixed ☹️
The experience of developing WinUI 3 App cannot catch up with UWP☹️ Lots of Win32 Interop and a broken template

**Comment by LegendaryBlair** [comment]
Already fixed.
