### ISSUE TITLE
Cannot specify requestedExecutionLevel=requireAdministrator in app.manifest of unpackaged self-contained app

### ISSUE THREAD

**Issue by Anish-V1073** [microsoft/WindowsAppSDK#3054]
In my .csproj, I have set < WindowsAppSDKSelfContained >true < /WindowsAppSDKSelfContained >
then, in my app.manifest, I have set < requestedExecutionLevel level="requireAdministrator" uiAccess="false" />

When I build, I get the error:

c1010001	Values of attribute "level" not equal in different manifest snippets.

**Comment by Levminer** [comment]
Any workaround for this?

**Comment by Anish-V1073** [comment]
Any updates on this?

**Comment by nathanAjacobs** [comment]
Same issue here.

**Comment by KWodarczyk** [comment]
it's not just unpackaged, same issue with packaged  + elevation + self-contained

**Comment by nathanAjacobs** [comment]
A workaround for unpacked is to create a launcher project that requires elevation that just launches the normal exe. I used .NET Framework 4.7.2 for the launcher project since that is bundled with most recent versions of Windows which allows the launcher exe to be small and not require a runtime install.

**Comment by Scottj1s** [comment]
The self-contained support was mistakenly inserting some fragments into the app manifest.  This issue has been resolved with Windows App SDK 1.2.

**Comment by Levminer** [comment]
@Scottj1s How is this fixed? I'm using Windows App SDK 1.2.221209.1. And I still get `Values of attribute "level" not equal in different manifest snippets.`

**Comment by christopher-rtf** [comment]
We build accessibility software.  System administrators would like to utilize MSIX installation and we'd like to upgrade from WPF and sparse packages to the latest technology (WinUI and the Windows App SDK).

We are trying to ship a WinUI app with uiAccess="true" (which is also an elevated state), and we are having similar issues as the OP.

Currently it seems like accessibility software is stuck using legacy technologies (WinForms/WPF, sparse packages) and unable to move forward with the newer technologies.  What can we do to help (e.g. pitch in on some code)?

Please note that there is also another issue tracking uiAccess-related issues:
https://github.com/microsoft/WindowsAppSDK/issues/1669

**Comment by ericlinf** [comment]
I'm on Windows App SDK 1.2.230118.102 and seeing this issue when specifying execution level. Tested with a brand new project using the WinUI 3 template wizard, with no changes except to the app manifest. Is there a workaround?

**Comment by KWodarczyk** [comment]
@ericlinf you have to make changes in two files

**Comment by ericlinf** [comment]
@KWodarczyk which files?

**Comment by KWodarczyk** [comment]
app.manifest
Package.appxmanifest

**Comment by KWodarczyk** [comment]
@ericlinf did you try the latest windowsappssdk ? They fixed it for packaged apps.

**Comment by cay7man** [comment]
Getting this with windowsappsdk 1.4 as well. Any workaround?

**Comment by schiaparelli5** [comment]
Same issue with unpackaged MAUI app. There is still no fix for this issue. I created a launcher app without any windows in console and this launcher app runs my MAUI app with admin rights.

**Comment by Anish-V1073** [comment]
I'm still facing the same issue with the latest App sdk. Any thoughts?
