### ISSUE TITLE
New templates adding Microsoft copyright notice

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/WindowsAppSDK#3143]
### Describe the bug

New 1.2 project and item templates are adding Microsoft copyright and MIT License notice to every file, which it shouldn't have as the templates are used to create your own project which isn't copyrighted by Microsoft.

### Steps to reproduce the bug

1. Create a new WinUI 3 project or item.
2. See the unnecessary copyright message.

```
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<!-- Licensed under the MIT License. See LICENSE in the project root for license information. -->
```

### IDE

Visual Studio 2022-preview

### Additional context

Templates version: 1.2.220902.1 (installed automatically by Visual Studio Installer).

**Comment by CompCodeNet** [comment]
Yes, upvoted and I find this copyright notice in one's own project code to be confusing. Request explanation, or please remove the copyright notice, the latter being preferable. Thank You.

**Comment by michael-hawker** [comment]
@bpulliam I still saw this creating a new project today, how do updates to the template ship? When should folks expect  to see this change hit their boxes? Thanks!

**Comment by duncanmacmichael** [comment]
This issue has been fixed in 1.2.4.

**Comment by theinas** [comment]
@duncanmacmichael I don't this issue has been entirely fixed. Updated today to 1.3.2 and I am still seeing the copy rights messages whenever creating a WinUI item
