### ISSUE TITLE
Self-Contained Deployment Redirect Activation COM Error

### ISSUE THREAD

**Issue by justinsoderstrom** [microsoft/WindowsAppSDK#3439]
### Describe the bug

The [AppInstance.RedirectActivationToAsync](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appinstance.redirectactivationtoasync?view=windows-app-sdk-1.2) method throws `COMException: Interface not registered (0x80040155)`  when using the SDK [self-contained](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps) deployment model. This doesn't occur when using the default framework-dependent model.

This is a problem when you want to use self-contained deployment and enforce [single instancing](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle#single-instanced-apps) in the application. There isn't a supported way in the framework to do this in the self-contained deployment model while this bug exists.

### Steps to reproduce the bug

I created a reproduction repository that features the issue: https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error. It is a packaged, Windows App SDK project using the SDK self-contained deployment model.

The [Program.cs](https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error/blob/master/WinAppSDKSelfContainedActivationError/Program.cs) file demonstrates the reproduction usage of [AppInstance.RedirectActivationToAsync](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appinstance.redirectactivationtoasync?view=windows-app-sdk-1.2).

Once you clone the repository, open it in Visual Studio 2022 do the following:

1. Place a breakpoint on line 63 in the [Program.cs](https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error/blob/master/WinAppSDKSelfContainedActivationError/Program.cs) file where [AppInstance.RedirectActivationToAsync](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appinstance.redirectactivationtoasync?view=windows-app-sdk-1.2) is used.
1. Run the application using `WinAppSDKSelfContainedActivationError (Package)` profile with Debugging.
1. While the app is running, try to launch the app again. The app is called `WinAppSDKSelfContainedActivationError`.
1. Step over `RedirectActivationToAsync` statement
1. You should see an `System.AggregateException` with an inner exception of `COMException: Interface not registered (0x80040155)` 

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Interface not registered (0x80040155))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1883
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2733
   at System.Threading.Tasks.Task.Wait() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2607
   at WinAppSDKSelfContainedActivationError.Program.<>c__DisplayClass3_0.<RedirectActivationTo>b__0() in C:\Code\Other\WinAppSDKSelfContainedActivationError\WinAppSDKSelfContainedActivationError\Program.cs:line 63
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2397
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2376
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268

Inner Exception 1:
COMException: Interface not registered (0x80040155)
```

If you open [WinAppSDKSelfContainedActivationError.csproj](https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error/blob/master/WinAppSDKSelfContainedActivationError/WinAppSDKSelfContainedActivationError.csproj) and remove `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` to change back to framework-dependent deployment, the error will not occur and will work as expected.

### Expected behavior

The [AppInstance.Activated](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appinstance.activated?view=windows-app-sdk-1.2) event should have been triggered and the  `OnActivated` method in [Program.cs](https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error/blob/master/WinAppSDKSelfContainedActivationError/Program.cs) on line 50 should have been called. There should be no `COMException: Interface not registered (0x80040155)` error raised.

### Screenshots

![COMBreakpoint](https://user-images.githubusercontent.com/22223310/219082361-6878120a-e6f9-41fc-84a6-83196e04f38b.PNG)
![COMException](https://user-images.githubusercontent.com/22223310/219081570-ee6b25ea-bac9-4f3a-9283-249a6effd26c.PNG)

### NuGet package version

Windows App SDK 1.2.3: 1.2.230118.102

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

### Additional context

I only tested this on Windows 10, version 21H2 using packaged (MSIX) deployment. I do not know if this also occurs on other Windows versions.

The current workaround is to switch back to using framework-dependent deployment of the SDK, but that is not an option in all scenarios.

The issue reproduction repository [README](https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error#readme) provides more information about the sample project. The [Program.cs](https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error/blob/master/WinAppSDKSelfContainedActivationError/Program.cs) file implementation that demonstrates the issue follows the implementation guidelines from the [Microsoft sample.](https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/Samples/AppLifecycle/Instancing/cs-winui-packaged/CsWinUiDesktopInstancing/CsWinUiDesktopInstancing/Program.cs)

**Comment by ritt-app** [comment]
I ran into the same problem on Windows 11, version 22H2, with Windows App SDK 1.2.230217.4.

**Comment by KWodarczyk** [comment]
How come this went unnoticed through msft testing ? either there is a gap in the validation or msft knows about this and ignored  that issue. I imagine that msft has tests for redirection cause it works in Framework dependent mode, so nobody thought to make a test for Self-contained mode ?

**Comment by koenvd** [comment]
Tried this as well but in our app this seems to be working while indeed the example app is crashing on my system as well.

We don't have a custom main method like in the example however (we're keeping the app single instance in the `OnLaunched` method).  So not sure if other people in this thread are in that case as well.

I updated the code in the sample app to do:
`Task.Run(async () =>
        {
            await keyInstance.RedirectActivationToAsync(args);
            redirectSemaphore.Release();
});`
and noticed the `OnActivated` event handler is not being called.  So somehow that mechanism seems to be stuck. After setting `WindowsAppSDKSelfContained` to false this indeed starts to work.

So not sure if this can be related to having a custom main method and somehow my app initialisation phase is a bit different where this starts working.

**Comment by KWodarczyk** [comment]
@koenvd is your app elevated ?

**Comment by koenvd** [comment]
> @koenvd is your app elevated ? Also custom main method was a workaround for elevation before it was fixed in 1.1

No. Full trust. But both of them are.

**Comment by koenvd** [comment]
So yeah. Seems like the sample code that fails is also working if I copy paste to a Packaged App with a `.wapproj` project file.  

No idea how this can have an impact though 🤔 . But maybe this can help you as well in short term @justinsoderstrom @ritt-app  @KWodarczyk .

**Comment by justinsoderstrom** [comment]
@koenvd I think you may be onto something with packaging the project using [Windows Application Packaging Project (.wapproj)](https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net). I haven't dug much into it yet, but I was able to create a quick SDK self-contained project using the same code as the example, but packages with the packaging project. The redirect logic seems to work on my machine with the small testing I did 😃 

Here is the project:
[SelfContainedPackagedProject.zip](https://github.com/microsoft/WindowsAppSDK/files/11063046/SelfContainedPackagedProject.zip)

My example uses the [single-project MSIX feature](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp) since that's the generally recommended format. I tried adding a packaging project to my example, but I run into a different error when trying to redirect. I still need to determine what's the difference between this project and the one that works.

**Comment by koenvd** [comment]
Yep. I also don't get what the difference is but seems to be somehow specific to a single project MSIX.

**Comment by koenvd** [comment]
Seems duplicate of https://github.com/microsoft/WindowsAppSDK/issues/3179 as well.

**Comment by koenvd** [comment]
Wondering @DrusTheAxe if you would have an idea what's going on here? 

`RedirectActivationToAsync` is not working when the app is self contained and built with a single project MSIX. This seems to be working fine in an app built with a Packaging Project (`.wapproj`).

I just would like to understand if moving to `.wapproj` is then the temporary workaround for this issue. Or if there still might be a risk this might not work on some devices even if the app is built with a `.wapproj` project.

Thanks!

**Comment by KWodarczyk** [comment]
@koenvd  instead of RedirectActivationToAsync you can use pinvoke version and works fine.

**Comment by koenvd** [comment]
Could you give a bit more details please @KWodarczyk? I'm not completely following tbh 🙂.

I need to PInvoke `RedirectActivation` somehow?

**Comment by KWodarczyk** [comment]
Not the "redirect activation" but you can use pinvoke to bring tunning app to front and kill the second one.

**Comment by koenvd** [comment]
Not sure this will work tbh @KWodarczyk .  I mean not sure if a second app instance can give focus to the first instance.  What I do know that works is if the `RedirectActivation` would work the first instance can use `PInvoke` to bring itself to the front.

And I can't pass the arguments as well off course in that mechanism. 

So would prefer a fix or at least a working workaround 😄 .

**Comment by KWodarczyk** [comment]
you can use 
```
        [DllImport("user32.dll")]
        private static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
``` 

and

```
var appProcess = Process.GetProcessById((int)appInstance.ProcessId);
ShowWindow(appProcess.MainWindowHandle, SwRestore);
````
 not sure how log we will wait for the fix

**Comment by bogdan-patraucean** [comment]
I just encountered the same issue on 1.3 preview.

**Comment by bogdan-patraucean** [comment]
@gabbybilka I think this two are duplicates.
https://github.com/microsoft/WindowsAppSDK/issues/3179

**Comment by koenvd** [comment]
Could we have an update on this @bpulliam @gabbybilka ? 

`RedirectActivation` in a self contained packaged app built without using a packaging project just doesn't seem to work 🤷‍♂️ .

**Comment by justinsoderstrom** [comment]
Agreed, I ultimately had to switch to a packaging project, and I've not run into any issues. 

I would like to know if there are any potential issues with using this approach as the work around until a fix is released.

**Comment by optsing** [comment]
Still not working for versions 1.4.230811000-preview2 and 1.3.230724000. Same error. Packaged application with a single msix project and WindowsAppSDKSelfContained=true, tested on Windows 11.
But it works when WindowsAppSDKSelfContained=false.

**Comment by optsing** [comment]
Same problem in release version 1.4 (1.4.230822000)

**Comment by AdriaanLarcai** [comment]
Still experiencing this issue in our unpackaged self contained release with the latest WindowsAppSDK, 1.4 (1.4.230822000).

**Comment by Lightczx** [comment]
It's the `winrt::Microsoft::Windows::AppLifecycle::IAppActivationArguments` that causing the error which iid is `{14F99EAF-1580-5062-BDC8-D5D1C31138FB}`

**Comment by DominicMaas** [comment]
Having the same issue over here as well

**Comment by juanmalm** [comment]
Same issue here

**Comment by jonwis** [comment]
Sorry for the long delay on getting to this.

The `IAppActivationArguments` interface uses metadata-based marshalling when sent between processes.  While the metadata-based marshaller is not well documented (we'll fix this) it basically needs to map the runtimeclass of the type to a WinMD file visible to the application. Metadata in the WinMD is used to synthesize a marshaller.  For this type, `Microsoft.Windows.AppLifecycle.winmd` from the Windows App SDK Runtime is necessary.

Apps that use the [shared distribution (the framework package)](https://learn.microsoft.com/windows/apps/windows-app-sdk/deploy-packaged-apps) get it automatically - FWP dependencies are resolved prior to app launch.

Apps that use [self-contained (packaged or otherwise)](https://learn.microsoft.com/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps) distribution must include the `.WinMD` files from the framework package in their package. The project machinery should be copying this for you.

Apps that are [unpackaged using the runtime framework](https://learn.microsoft.com/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=csharp) must use the Bootstrapper to ensure the framework package is pulled into your process before using any part of the Windows App Runtime.

For folks still having this problem (hi @asklar !) can you let me know which configuration you're in?

If you're in unpackaged, make sure your build scripts are copying the WinMDs and support files into your deployment vehicle for delivery to your customers.

**Comment by jonwis** [comment]
Oh see also #2006 where @BenJKuhn talks about which files need to be retained vs copied.

I have a _hunch_ that the "single file" `dotnet publish` mode is discarding the WinMDs and preventing this system from working.  The mapping of runtimeclass to file name is trivial - we just look for `Foo.Bar.Bas.Zot.WinMD` then `Foo.Bar.Bas.WinMD` then `Foo.Bar.WinMD`, etc. There's no means of redirecting to say "hey this DLL contains this WinMD you can use!" at this time.

**Comment by asklar** [comment]
@jonwis I'm hitting this with single project framework package (via nuget)

**Comment by juanmalm** [comment]
@jonwis your workaround is not working for me. I cannot build the app after referencing the winmd file:

`1>C:\Program Files\dotnet\sdk\8.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1162,5): error NETSDK1130: Microsoft.Windows.AppLifecycle.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130`

**Comment by Lightczx** [comment]
They do have Stroage API improved in WASDK 1.8 though.

**Comment by ssparach** [comment]
Thank you for your contribution and the detailed repro @justinsoderstrom 

After testing the issue using your repro and updating to the latest stable version of WindowsAppSDK, we’re no longer able to reproduce the problem. With the newer package version, the .winmd file is also now being placed under the bin folder.

Because the issue appears to be resolved in newer builds, I’m closing this out as completed. If you’re still encountering this behavior on your end, please feel free to open a new issue with updated details, and we’ll be happy to take another look.

Thanks again for helping improve the project!

**Comment by elibroftw** [comment]
I can reproduce this issue using WinAppSDK 2.2 on Windows 10 22H2 (ISO created from the media installation tool). Is there a workaround or a fix to support the older OS? It affects our ability to provice the best onboarding experience for users still using windows 10.

Our app is WinUI unpackaged self-contained and uses sparse package for identity purposes.

"System.Runtime.InteropServices.COMException (0x80040155): Interface not registered\r\n\r\nC:\\__w\\1\\s\\dev\\AppLifecycle\\RedirectionRequest.cpp(57)\\Microsoft.WindowsAppRuntime.dll!00007FFAAC7D9C2F: (caller: 00007FFAAC6CA57F) Exception(1) tid(2518) 80040155 Interface not registered\r\n    CallContext:[\\QueueRequest] \n\r\n   at MyApp.App.<>c__DisplayClass16_0.<RedirectActivationTo>b__0() in App.xaml.cs:line 235","pid":8640}

```cs
[STAThread]
    static void Main()
    {
        ConfigureLogging();
        Log.Info("App instance launched; Logging initialized");
        try {
            WinRT.ComWrappersSupport.InitializeComWrappers();
            Log.Info("COM wrappers initialized");
        } catch (Exception ex)
        {
            Log.Error($"Failed to initialize COM wrappers. Not pumping COM. {ex}");
        }

        if (DecideRedirection())
        {
            // Activation has been handed to the primary instance
            return;
        }

        Start((p) =>
        {
            var context = new DispatcherQueueSynchronizationContext(DispatcherQueue.GetForCurrentThread());
            SynchronizationContext.SetSynchronizationContext(context);
            _ = new App();
        });
    }

private static bool DecideRedirection()
    {
        var keyInstance = AppInstance.FindOrRegisterForKey("primary");
        if (keyInstance.IsCurrent)
        {
            // Handle redirect activations of subsequent launches
            keyInstance.Activated += OnRedirectActivated;
            return false;
        }
        // Subsequent launches will redirect activation to the primary instance
        var activationArgs = AppInstance.GetCurrent().GetActivatedEventArgs();
        Log.Info($"Secondary instance; redirecting activation (kind={activationArgs.Kind}) to primary instance (pid {keyInstance.ProcessId})");
        RedirectActivationTo(activationArgs, keyInstance);
        return true;
    }

private static void RedirectActivationTo(AppActivationArguments activationArgs, AppInstance keyInstance)
    {
        // A single-thread apartment (STA) must pump messages while idle to avoid jamming up window broadcasts
        // The redirect activation is waited using a method that continues dispatching messages
        using var redirectComplete = new ManualResetEvent(false);
        var redirectTimeout = TimeSpan.FromSeconds(5);
        using var cts = new CancellationTokenSource(redirectTimeout);
        Task.Run(() =>
        {
            try
            {
                keyInstance.RedirectActivationToAsync(activationArgs).AsTask(cts.Token).GetAwaiter().GetResult();
                Log.Info("Redirected activation to primary instance");
            }
            catch (OperationCanceledException)
            {
                Log.Error($"Failed to activate existing instance; timed out after {redirectTimeout}.");
            }
            catch (Exception ex)
            {
                Log.Error("Failed to activate existing instance", ex);
            }
            finally
            {
                redirectComplete.Set();
            }
        });
        var handle = new HANDLE(redirectComplete.SafeWaitHandle.DangerousGetHandle());
        PInvoke.CoWaitForMultipleObjects((uint)CWMO_FLAGS.CWMO_DEFAULT, PInvoke.INFINITE, [handle], out _);
    }
```

I've uploaded a diff of the "fix"

[windows-10-activation-fallback.diff.txt](https://github.com/user-attachments/files/30012819/windows-10-activation-fallback.diff.txt)
