### ISSUE TITLE
Cannot install version 1.3: DDLM package not found

### ISSUE THREAD

**Issue by KarelChanivecky** [microsoft/WindowsAppSDK#3855]
### Describe the bug

Cannot install version 1.3.
The output is as such:
```
PS C:\Users\User\Downloads> .\WindowsAppRuntimeInstall1.3.exe
Installing license: MSIX_MAINPACKAGE_LICENSE
Install License result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install License result : 0x0
Deploying package: MicrosoftCorporationII.WinAppRuntime.Main.1.3_3000.934.1904.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Provisioning result : 0x0
Deploying package: Microsoft.WinAppRuntime.DDLM.3000.934.1904.0-x6_3000.934.1904.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Provisioning result : 0x80073cf1 Package was not found.
Deploying package: Microsoft.WinAppRuntime.DDLM.3000.934.1904.0-x8_3000.934.1904.0_x86__8wekyb3d8bbwe
Package deployment result : 0x0
Provisioning result : 0x80073cf1 Package
```

v1.4 does install properly. Is it possible that there are broken links in the old installer now that 1.4 has been released.

I have tried obtaining installers from:
https://aka.ms/windowsappsdk/1.3/1.3.230724000/windowsappruntimeinstall-x64.exe
and 
https://aka.ms/windowsappsdk/1.3/latest/windowsappruntimeinstall-x64.exe

### Steps to reproduce the bug

1. Download 1.3 installer from 
    https://aka.ms/windowsappsdk/1.3/1.3.230724000/windowsappruntimeinstall-x64.exe
    or
    https://aka.ms/windowsappsdk/1.3/latest/windowsappruntimeinstall-x64.exe
2. Run the installer with admin privileges

RESULT:
Only the following is installed:
![image](https://github.com/microsoft/WindowsAppSDK/assets/46802352/86a03cbd-27a9-4fae-b07f-c85c105f67ed)

### Expected behavior

Packages akin to the ones in the screenshot, but with the proper version for 1.3 appear:
![image](https://github.com/microsoft/WindowsAppSDK/assets/46802352/b6d53c32-8e0e-479d-b976-7a2c3b41a4a7)

### NuGet package version

None

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

**Comment by DHancock** [comment]
Similar to #3602 ?

**Comment by pratikone** [comment]
A more accurate way to identify which all windows app runtime packages is by launching powershell in admin mode and running : 
`Get-AppxPackage -allusers *windowsappruntime*`. 

Could you do it and print its output here so that we can see what all is installed.

**Comment by SuinegXY** [comment]
@DrusTheAxe 
this problem is still exist.
when i install v1.5 first and install v1.4 next,
the ddlm 1.4 is not installed still.

for the result, my unpackaged app can't start,
it notice that
"This application requires the Windows App Runtime"
"Version 1.4"
"(MSIX package version >= 4000.964.11.0)"

**Comment by pratikone** [comment]
Thanks for posting an update. We have fixed some of these issues with 1.4.3 onwards so it is understandable some of the issue is gone. There seem to be more remaining and I will be investigating it. 
Thanks for posting the output

**Comment by SuinegXY** [comment]
I tried the V1.4.5, and the problem was still exist,
I installed the V1.5.1 first, and installed the V1.4.5 next.
The V1.4 App can't start

I used the command `powershell (get-appxpackage micro*win*appruntime*).packagefullname`
The output was 
`C:\Users\WDAGUtilityAccount>powershell (get-appxpackage micro*win*appruntime*).packagefullname
Microsoft.WindowsAppRuntime.CBS_4000.1027.2341.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.5_5001.70.1338.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.5_5001.70.1338.0_x86__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Main.1.5_5001.70.1338.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.5001.70.1338.0-x6_5001.70.1338.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.5001.70.1338.0-x8_5001.70.1338.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.4_4000.1136.2333.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.4_4000.1136.2333.0_x86__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Main.1.4_4000.1136.2333.0_x64__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Singleton_5001.70.1338.0_x64__8wekyb3d8bbwe`

**Comment by KarelChanivecky** [comment]
FYI this also happens when using winget:
![image](https://github.com/microsoft/WindowsAppSDK/assets/46802352/e2426528-9088-49ee-adb2-96a36b660fe9)

**Comment by legistek** [comment]
So what's the solution? Trying to install this on a Windows Server build server and it won't install.

**Comment by DrusTheAxe** [comment]
> Get-AppxPackage -allusers *windowsappruntime*

BTW WinAppSDK's package Names vary (quite a bit) so that filter won't catch them all. For future reference this is a better filter

```
Get-AppxPackage -allusers micro*win*app*run*
```
