### ISSUE TITLE
Windows App SDK - Visual Studio Warning NETSDK1206

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WindowsAppSDK#3959]
### Describe the bug

Upgrading an entire project that uses Windows App SDK, to .Net 8.0, give this warning:
![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/b2bbb531-f614-4701-8954-014a25e89689)
I've already changed my project's <RuntimeIdentifiers> to use the portable RIDs:
![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/862c26c6-2a3c-4571-aef2-b70643ea18d0)

### Steps to reproduce the bug

Upgrade your existing project to use .Net 8.

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
The [release notes](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#known-issues) give two steps that you should do.
1) [Set UseRidGraph to true](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list#recommended-action).
2) Use the portable runtime identifiers.
Your description only describes doing the second step. Also, the team has stated that proper .NET 8 support would come after .NET 8 is released. Since there hasn't been a release of the Windows App SDK since yesterday, then this is a known issue and will be fixed in an upcoming version.

**Comment by DJRM2021** [comment]
> The [release notes](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#known-issues) give two steps that you should do.
> 
> 1. [Set UseRidGraph to true](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list#recommended-action).
> 2. Use the portable runtime identifiers.
> 
> Your description only describes doing the second step. Also, the team has stated that proper .NET 8 support would come after .NET 8 is released. Since there hasn't been a release of the Windows App SDK since yesterday, then this is a known issue and will be fixed in an upcoming version.

Thanks for the help @DarranRowe 

PS Since this is already a known issue, and would likely be fixed in future releases, this bug ticket will now be closed.

**Comment by ctmatt** [comment]
just because it's known and would likely be fixed doesn't mean you should close it.

9 months later and it's still not fixed

**Comment by DJRM2021** [comment]
> just because it's known and would likely be fixed doesn't mean you should close it.
> 
> 9 months later and it's still not fixed

It is fixed in the latest stable and preview releases. Thanks!

**Comment by ctmatt** [comment]
by the way, humor me, what is the latest stable release?

**Comment by ctmatt** [comment]
in project nuget packages (main and transient) i only see one Microsoft.WindowsAppSDK,  v1.5.240802000

is it possible the old version is latched on like a barnacle to this project?  It used to use v1.4 unless i'm wrong.

**Comment by ctmatt** [comment]
I think I updated the dotnet SDK and the problem went away, unsure, was trying all sorts of stuff.
