### ISSUE TITLE
Incorrect v1.6exp1 error

### ISSUE THREAD

**Issue by dotMorten** [microsoft/WindowsAppSDK#4473]
### Describe the bug

When adding the latest 1.6.240531000-experimental1 nuget package, I'm met with the following error:

```
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error : This version of the Windows App SDK requires Microsoft.Windows.SDK.NET.Ref 10.0.19041.35-preview;10.0.19041.35-preview or later, which can be added with:
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :         <PropertyGroup>
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :             <WindowsSdkPackageVersion>10.0.19041.35-preview;10.0.19041.35-preview</WindowsSdkPackageVersion>
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :         </PropertyGroup>
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :
```
Adding this to the project will result in a build-error. The string
`10.0.19041.35-preview;10.0.19041.35-preview`
should be changed to
`10.0.19041.35-preview`

### Steps to reproduce the bug

1. Create a new WinUI project.
2. Update the nuget package to latest WindowsAppSDK 1.6.240531000-experimental1

### Expected behavior

Don't repeat the version number inside the WindowsSdkPackageVersion tag twice
```
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error : This version of the Windows App SDK requires Microsoft.Windows.SDK.NET.Ref 10.0.19041.35-preview;10.0.19041.35-preview or later, which can be added with:
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :         <PropertyGroup>
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :             <WindowsSdkPackageVersion>10.0.19041.35-preview</WindowsSdkPackageVersion>
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :         </PropertyGroup>
1>C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.6.240531000-experimental1\buildTransitive\Microsoft.WindowsAppSDK.targets(84,9): error :
```

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/1378165/f6ae5174-f6ab-4cc1-aa03-dd85a097726f)

### NuGet package version

Windows App SDK 1.6 Experimental 1: 1.6.240531000-experimental1

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by Scottj1s** [comment]
Thanks @dotMorten - will be fixed in the Experimental 2 release.

**Comment by AndrewKeepCoding** [comment]
The error message indicates that you need to add somewhere:
```xml
<PropertyGroup>
    <WindowsSdkPackageVersion>10.0.19041.35-preview;10.0.19041.35-preview</WindowsSdkPackageVersion>
</PropertyGroup>
```
and when you double-click the error message, it opens the file **Microsoft.WindowsAppSDK.targets** which is inside the cached NuGet packages.
If possible, it might be better if it opens the project file instead.

**Comment by dotMorten** [comment]
That's not quite how errors thrown by build .target files work though.
Visual studio opens build errors where they occur

**Comment by AndrewKeepCoding** [comment]
Yeah. I figured. How about mentioning "project file" in the error message?
I think that it's confusing for devs new with .NET projects😅

**Comment by Scottj1s** [comment]
Fixed in WinAppSDK 1.6 Preview 2

**Comment by gabriel-vanca** [comment]
Had the same error with a new freshly made project in VS 2022. Fixed it by adding:

``` xaml
<WindowsSdkPackageVersion>10.0.26100.38</WindowsSdkPackageVersion>
```

after

``` xaml
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.20348.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
```

**Comment by gabriel-vanca** [comment]
Well, I'm on version 1.6 and I'm still having the issue. Unless I've seriously misconfigured something.

![image](https://github.com/user-attachments/assets/735fad8a-bce4-484e-9d25-414df4308ea5)

**Comment by dotMorten** [comment]
@gabriel-vanca The generated error isn't the bug (it's actually quite helpful since it is required for now - see release notes). The message in the error was the issue and it is fixed.
The error before the fix was:
`<WindowsSdkPackageVersion>10.0.19041.35-preview;10.0.19041.35-preview</WindowsSdkPackageVersion>`
where the error was supposed to be:
`<WindowsSdkPackageVersion>10.0.19041.35-preview</WindowsSdkPackageVersion>`

**Comment by gabriel-vanca** [comment]
Get it now. Thanks!

**Comment by mcyenikoylu** [comment]
I create a new empty WinUI3 project and it doesn't compile. Isn't this an error, you say? :)

**Comment by gabriel-vanca** [comment]
Yes, I agree a default template not compiling should be treated more seriously.

**Comment by codendone** [comment]
Tracking future improvement here via #4734.
