### ISSUE TITLE
ImageScanner ScanFilesToFolderAsync throws System.Runtime.InteropServices.COMException after 1st scan

### ISSUE THREAD

**Issue by NGeras** [microsoft/WindowsAppSDK#4745]
### Describe the bug

When app is updated to WinAppSDK 1.6 and WindowsSdkPackageVersion is set to 10.0.22621.38 or if app is on WinAppSDK 1.5 and WindowsSdkPackageVersion is set to 10.0.22621.38 ScanFilesToFolderAsync method of ImageScanner throws a System.Runtime.InteropServices.COMException after first or second scan but scanned images is saved to Pictures folder successfully.

### Steps to reproduce the bug

1. Create new WinAppSDK project
2. Update WinApSDK to 1.6 and add `<WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>`
3. Add to myButton_Click
```
StorageFile scannedFile;
DeviceInformationCollection devices = await DeviceInformation.FindAllAsync(DeviceClass.ImageScanner);
var device = devices[0];
ImageScanner scanner = await ImageScanner.FromIdAsync(device.Id);

var config = scanner.FlatbedConfiguration;
config.Format = ImageScannerFormat.DeviceIndependentBitmap;
Windows.Storage.StorageFolder sf = Windows.Storage.KnownFolders.PicturesLibrary;
var result = await scanner.ScanFilesToFolderAsync(ImageScannerScanSource.Flatbed, sf);
if (result != null)
{
    scannedFile = await StorageFile.GetFileFromPathAsync(result.ScannedFiles.FirstOrDefault().Path);
    using (var fileStream = await scannedFile.OpenAsync(Windows.Storage.FileAccessMode.Read))
    {
        BitmapImage bitmapImage = new BitmapImage();
        await bitmapImage.SetSourceAsync(fileStream);
        bitmapImages.Add(bitmapImage);
    }
    await scannedFile.DeleteAsync();
}
```
4. Click the button, wait till scanning is completed and click again, on second or third time the COMException is thrown

### Expected behavior

ScanFilesToFolderAsync  should behave as it was in 1.5 and on older WindowsSdkPackageVersion

### Screenshots

![image](https://github.com/user-attachments/assets/487639d1-cec5-4c95-9019-c61673536a6a)

### NuGet package version

Windows App SDK 1.6.0: 1.6.240829007

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Test application
[ScannerTestApp.zip](https://github.com/user-attachments/files/17127748/ScannerTestApp.zip)

**Comment by codendone** [comment]
[internal bug for owners of this API](https://task.ms/55753068)

**Comment by jeremy-visionaid** [comment]
I just had a user report a crash in our application for something very similar:
On the second call to `ImageScanner.ScanFilesToFolderAsync`, `AsTask` can throw a `COMException`  with `0x80000019` i.e. `E_ASYNC_OPERATION_NOT_STARTED`

```
System.Runtime.InteropServices.COMException (0x80000019)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Foundation.IAsyncInfoMethods.get_Status(IObjectReference _obj)
   at ABI.Windows.Foundation.IAsyncOperationWithProgressImpl`2.get_Status()
   at System.WindowsRuntimeSystemExtensions.AsTask[TResult,TProgress](IAsyncOperationWithProgress`2 source, 
```

I'm using `<TargetFramework>net8.0-windows10.0.19041</TargetFramework>` and although I haven't set it explicitly, 
I believe `WindowsSdkPackageVersion` is resolving to 10.0.19041.56

**Comment by jeremy-visionaid** [comment]
Customers confirm that reverting `WindowsSdkPackageVersion` to 10.0.19041.34 resolves this issue. I cannot bisect any further than this since I cannot repro the issue locally.

**Comment by jeremy-visionaid** [comment]
As I just found out Windows App SDK 1.6 requires WindowsSdkPackageVersion 10.0.x.38 or later. Consequently, it's not possible to ship a dotnet 9 MAUI scanning app.

**Comment by jeremy-visionaid** [comment]
Not sure if/when this got fixed, but it at least appears to be working for me in WinAppSDK 1.8.260804001

**Comment by jeremy-visionaid** [comment]
I spoke too soon, although I can't repro locally, for `net10.0-windows10.0.26100.0` and `WindowsSdkPackageVersion` unset with .NET SDK 10.0.400, I'm seeing `E_ASYNC_OPERATION_NOT_STARTED`  in the field, similarly to before.

```
System.Runtime.InteropServices.COMException (0x80000019)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at System.Runtime.ExceptionServices.InternalCalls.<RhpSfiNext>g____PInvoke|1_0(StackFrameIterator* __pThis_native, UInt32* __uExCollideClauseIdx_native, Boolean* __fUnwoundReversePInvoke_native, Boolean* __fIsExceptionIntercepted_native)
   at ABI.Windows.Foundation.IAsyncInfoMethods.get_Status(IObjectReference _obj)
   at ABI.Windows.Foundation.IAsyncOperationWithProgressImpl`2.get_Status()
   at System.WindowsRuntimeSystemExtensions.AsTask[TResult,TProgress](IAsyncOperationWithProgress`2 source, CancellationToken cancellationToken, IProgress`1 progress)
   at System.Runtime.ExceptionServices.InternalCalls.<RhpSfiNext>g____PInvoke|1_0(StackFrameIterator* __pThis_native, UInt32* __uExCollideClauseIdx_native, Boolean* __fUnwoundReversePInvoke_native, Boolean* __fIsExceptionIntercepted_native)
```

**Comment by jeremy-visionaid** [comment]
@codendone This is getting pretty tight now. As an app developer, I'm responsible for providing security updates, and .NET 8.0 will be out of support come November. It appears there's no path to shipping an application on .NET 10 where scanning works reliably using the Windows Runtime APIs. It has been 2 years since the regression was identified, do you know if there has been any movement on this internally?

**Comment by codendone** [comment]
@jeremy-visionaid Great timing on your ping. Looking at the internal bug, it looks like the fix was released last week as part of https://support.microsoft.com/en-us/servicing/os/windows-11/2026/08/kb5120998-windows-11-24h2-25h2-update. The fix should roll out to most users when they pick up the standard September updates for Windows.

I'm closing this issue, now that the fix is rolling out.

**Comment by jeremy-visionaid** [comment]
Nice one, thanks!

**Comment by jeremy-visionaid** [comment]
@codendone Unfortunately, customers report that the scanning error still occurs as of OS build 26200.9457. Is someone able to reopen the internal issue, or otherwise verify that it was actually supposed to be fixed as of 26200.9278? It's not mentioned in the release notes.

**Comment by lauren-ciha** [comment]
Thank you for letting us know. I have added your comment to the internal issue.
