### ISSUE TITLE
[Single Project MSIX] Generated appxsym/msixsym has Managed PDB when Native AOT is enabled

### ISSUE THREAD

**Issue by dongle-the-gadget** [microsoft/WindowsAppSDK#5415]
### Describe the bug

Even with `PublishAot=true` in the project, Single Project MSIX produces a symbol file that contains Managed PDBs, not Native AOT PDBs.

### Steps to reproduce the bug

1. Create a blank UWP .NET 9 application (or a blank Single Project MSIX WinUI 3 application)
2. In the csproj, make sure `PublishAot` is `true`.
3. Right click the project in Solution Explorer and go to Package and Publish > Create App Package
4. Make sure the shown dialog has "Sideloading" selected and go through the steps in the dialog.
5. Wait until build completes and open the package directory, see the presence of an appxsym or msixsym file.
6. Rename the appxsym/msixsym extension to zip and extract the PDB within.
7. Notice that the PDB file is only a few kilobytes large, which is too small for Native AOT PDBs.

### Expected behavior

The PDB file within the symbol files generated should be a few megabytes at least.

### NuGet package version

Windows App SDK 1.7.1: 1.7.250401001

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

### Additional context

This also occurs in Microsoft.Windows.SDK.BuildTools.MSIX version 1.7.20250508.1

**Comment by dongle-the-gadget** [comment]
This is not an UWP exclusive issue - any Native AOT programs (regardless of UWP, WinUI 3, Console, etc.) packaged using Single-Project MSIX are affected.

**Comment by guimafelipe** [comment]
Fixed in https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools.MSIX/1.7.260425100

**Comment by dongle-the-gadget** [comment]
@guimafelipe I've tried this with `1.7.260501103`, it didn't work. I still get only Managed PDB in my AppxSym files. Worse, it doesn't include the main app, but only the libraries (main app is `MicaForEveryone.App.pdb` at 66 MB, these files are about 20 KB).

<img width="460" height="122" alt="" src="https://github.com/user-attachments/assets/d511e527-4d82-4c55-88ae-f2a525c63846" />

**Comment by guimafelipe** [comment]
@dongle-the-gadget Can you send me your .binlog so I can analyze it? Also, if your project is open source, can you send me the link too so I can try to reproduce it locally?

**Comment by dongle-the-gadget** [comment]
(binlog updated because I accidentally used the old NuGet for that, here's the fixed one)

Here's the binlog (rename the file extension): [CentralNode_devenv_PID=34024_x64_BuildManager_Default.zip](https://github.com/user-attachments/files/27369662/CentralNode_devenv_PID.34024_x64_BuildManager_Default.zip)

Source code: https://github.com/MicaForEveryone/MicaForEveryone

**Comment by guimafelipe** [comment]
> (binlog updated because I accidentally used the old NuGet for that, here's the fixed one)
> 
> Here's the binlog (rename the file extension): [CentralNode_devenv_PID=34024_x64_BuildManager_Default.zip](https://github.com/user-attachments/files/27369662/CentralNode_devenv_PID.34024_x64_BuildManager_Default.zip)
> 
> Source code: https://github.com/MicaForEveryone/MicaForEveryone

Thanks, that helped a lot. I am working on a fix and adding this scenario to the tests. My previous fixed worked on single project AOT, but on Multi-project we are copying libraries (managed .pdbs by design) but this was making the native .pdb not being included.

**Comment by guimafelipe** [comment]
Now the native pdb is always added and the managed ones are removed from the final folder. Fix on [1.7.260513100](https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools.MSIX/1.7.260513100).

**Comment by dongle-the-gadget** [comment]
@guimafelipe I just checked it. `.msixupload` files still contain the wrong symbols. Binlog for reference (rename extension): [msbuild.zip](https://github.com/user-attachments/files/27746620/msbuild.zip)

<img width="800"  alt="" src="https://github.com/user-attachments/assets/e3d154c2-184b-48b0-a7bd-ba75001d2a6e" />

`.appxsym` files outside of `.msixupload` are correct.

<img width="800" alt="" src="https://github.com/user-attachments/assets/50df8ed9-fa47-4952-a7a9-519abba3adaf" />

**Comment by guimafelipe** [comment]
> `.appxsym` files outside of `.msixupload` are correct.

While fixing this issue I missed the upload path and fixed only the .appxsym path. They are two different code that are almost identical, so the fix is just duplicate what I did to the appsym path to the upload path. I will try to make it ready as soon as possible. Thank you for the quick feedback

**Comment by guimafelipe** [comment]
> [@guimafelipe](https://github.com/guimafelipe) I just checked it. `.msixupload` files still contain the wrong symbols. Binlog for reference (rename extension): [msbuild.zip](https://github.com/user-attachments/files/27746620/msbuild.zip)

I released a new version of the package https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools.MSIX/1.7.260518100 with the fix now also applied in the upload version of the app symbols.
